Create the following Numpy array of 32-bit integers

    array([[1, 1, 1, 1, 1],
           [0, 1, 1, 1, 1],
           [0, 0, 1, 1, 1],
           [0, 0, 0, 1, 1],
           [0, 0, 0, 0, 1]])



In [1]:
import numpy as np
matrix = np.ones([5,5],np.int32)
answer = np.triu(matrix,k=0)

Create the following Numpy array of 16-bit integers

    array([[ 1,  2,  3,  4,  5],
           [ 0,  6,  7,  8,  9],
           [ 0,  0, 10, 11, 12],
           [ 0,  0,  0, 13, 14],
           [ 0,  0,  0,  0, 15]])

In [2]:
import numpy as np
matrix = np.zeros(25, np.int16).reshape(5,5)
iu1 = np.triu_indices(5)
matrix[iu1] = np.arange(1,16)

answer = matrix

Given the following two-dimensional array, set the diagonal element to the average of the columns in each respective row not counting the diagonal element in each row. Note that the diagonal element itself is not part of the calculation. It is just a placeholder for the result.

    [[0,   3, 14, 13, 12],
     [13,  0,  8,  5, 11],
     [11, 11,  0, 12, 10],
     [11, 12,  1,  0, 10],
     [13, 12, 11,  4,  0]]
     
In this case, your answer should look like the following

    [[ 10.5 ,   3.  ,  14.  ,  13.  ,  12.  ],
     [ 13.  ,   9.25,   8.  ,   5.  ,  11.  ],
     [ 11.  ,  11.  ,  11.  ,  12.  ,  10.  ],
     [ 11.  ,  12.  ,   1.  ,   8.5 ,  10.  ],
     [ 13.  ,  12.  ,  11.  ,   4.  ,  10.  ]]

In the general case, the diagonal elements won't necessarily be equal to zero like they are here!

In [3]:
def average_into_diagonal(x):
    '''
    return average of non-diagonal elements with values filled into the diagonal
    
    :param: x (square two-dimensional input array)
    :type: numpy array
    :returns: numpy array

    '''
    assert isinstance(x,np.ndarray)
    assert x.ndim == 2
    assert x.shape[0] == x.shape[1] # square arrays only
    
    x = x.astype(float)
    len = x.shape[0]
    for i in range(len):
        x[i,i] = 0
        x[i,i] = 1.0*np.sum(x[i,:])/(len-1)
        
    return x
    

x = np.array([[10,   3, 14, 13, 12],
 [13,  10,  8,  5, 11],
 [11, 11,  10, 12, 10],
 [11, 12,  1,  10, 10],
 [13, 12, 11,  4,  10]])
average_into_diagonal(x)

array([[ 10.5 ,   3.  ,  14.  ,  13.  ,  12.  ],
       [ 13.  ,   9.25,   8.  ,   5.  ,  11.  ],
       [ 11.  ,  11.  ,  11.  ,  12.  ,  10.  ],
       [ 11.  ,  12.  ,   1.  ,   8.5 ,  10.  ],
       [ 13.  ,  12.  ,  11.  ,   4.  ,  10.  ]])